# Site
title: Tal Perry
description: Thoughts on tech, finance and art
logo: halve.png                                       # Site logo
locale: en_US
url: http://www.talperry.com
# Left Block Images
background:
  homepage: images/gentree.jpg                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-64131153-1

# Social Links
email:             talolard@gmail.com
#google.plus:        username
twitter:            thetalperry
#facebook:           username
github:             talolard
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          tal-perry-b561212a
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
